ccam/academics/seac/urls.py
from django.urls import path

from ccam.academics.seac import views

urlpatterns = [
    path(
        "knowledge-certificates/list", views.SeacKnowledgeCertificatesListView.as_view(), name="knowledge_certificates"
    ),
    path("courses-dispensal/list", views.SeacSubjectDispensalListView.as_view(), name="courses_dispensal"),
    path(
        "knowledge-certificates/detail/<int:pk>/",
        views.SeacKnowledgeCertificateUpdateView.as_view(),
        name="knowledge_certificate_detail",
    ),
    path(
        "courses-dispensal/detail/<int:pk>",
        views.SeacCoursesDispensalUpdateView.as_view(),
        name="courses_dispensal_detail",
    ),
    path(
        "knowledge-certificate-rejection/<int:pk>/",
        views.RejectStudentKnowledgeCertificateFormView.as_view(),
        name="reject_knowledge_certificate",
    ),
    path(
        "subject-dispensal-rejection/<int:pk>/",
        views.RejectStudentSubjectDispensalFormView.as_view(),
        name="reject_subject_dispensal",
    ),
]

ccam/academics/students/urls.py
from django.urls import path

from ccam.academics.students import views

urlpatterns = [
    path(
        "knowledge-certificates/create/",
        views.KnowledgeCertificateCreateView.as_view(),
        name="knowledge_certificates_create",
    ),
    path(
        "knowledge-certificates/list/",
        views.KnowledgeCertificateListView.as_view(),
        name="knowledge_certificates_list",
    ),
    path("subject-dispensals/create/", views.SubjectDispensalCreateView.as_view(), name="subject_dispensals_create"),
    path("subject-dispensals/list/", views.SubjectDispensalListView.as_view(), name="subject_dispensals_list"),
    path(
        "subject-dispensals/check-justification/<int:pk>/",
        views.SubjectDispensalApprovalCheckView.as_view(),
        name="subject_dispensal_denial_check",
    ),
    path(
        "knowledge-certificates/check-justification/<int:pk>/",
        views.KnowledgeCertificateApprovalCheckView.as_view(),
        name="knowledge_certificate_denial_check",
    ),
]

ccam/academics/urls.py
from django.urls import path

from ccam.academics.coordinators.urls import urlpatterns as coordinators_urls
from ccam.academics.seac.urls import urlpatterns as seac_urls
from ccam.academics.students.urls import urlpatterns as students_urls
from ccam.academics.teachers.urls import urlpatterns as teachers_urls
from ccam.academics.views import CourseSubjects

app_name = "academics"

urlpatterns = [path("course-subjects/", CourseSubjects.as_view(), name="course_subjects")]

urlpatterns += seac_urls
urlpatterns += coordinators_urls
urlpatterns += students_urls
urlpatterns += teachers_urls

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ccam.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("people/", include("people.urls")),
    path("academics/", include("academics.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ccam/academics/coordinators/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from ccam.academics.filters import CommitteeFilterSet, SubjectFilterSet
from ccam.academics.forms import AddTeachersToCommitteeForm, CommitteeForm, SubjectForm
from ccam.academics.models import Committee, Subject
from ccam.core.views import FilteredListView
from ccam.people.mixins import UserIsCourseCoordinatorTestMixin
from ccam.people.teachers.filters import TeacherFilterSet
from ccam.people.teachers.models import Teacher


class SubjectCreateView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, SuccessMessageMixin, CreateView):
    model = Subject
    success_url = reverse_lazy("people:coordinators:home")
    success_message = _("Disciplina cadastrada com sucesso!")
    template_name = "academics/coordinators/subject_form.html"
    form_class = SubjectForm

    @transaction.atomic
    def form_valid(self, form):
        subject = form.save(commit=False)
        subject.created_by = self.request.user
        subject.updated_by = self.request.user
        response = super().form_valid(form)
        subject.course.add(self.request.user.person.coordinator_person.course)
        return response


class SubjectListView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, FilteredListView):
    model = Subject
    filterset_class = SubjectFilterSet
    template_name = "academics/coordinators/subject_list.html"
    paginate_by = settings.PAGINATE_BY

    def get_queryset(self):
        coordinator_course = self.request.user.person.coordinator_person.course
        return Subject.objects.filter(course__in=[coordinator_course])


class SubjectUpdateView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, SuccessMessageMixin, UpdateView):
    model = Subject
    form_class = SubjectForm
    success_message = _("Disciplina atualizada com sucesso!")
    success_url = reverse_lazy("academics:subjects_list")
    template_name = "academics/coordinators/subject_form.html"


class SubjectDetailView(LoginRequiredMixin, DetailView):
    template_name = "academics/coordinators/subject_detail.html"
    model = Subject
    context_object_name = "subject"


class SubjectDeleteView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, SuccessMessageMixin, DeleteView):
    model = Subject
    template_name = "academics/coordinators/subject_check_delete.html"
    success_url = reverse_lazy("academics:subjects_list")
    success_message = _("Disciplina deletada com sucesso!")


class CommitteeCreateView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, SuccessMessageMixin, CreateView):
    model = Committee
    form_class = CommitteeForm
    template_name = "academics/coordinators/committee_form.html"
    success_message = _(
        "Banca criada com sucesso! Você pode adicionar os professores que irão compô-la na página de listagem"
    )
    success_url = reverse_lazy("people:coordinators:home")
    paginate_courses_by = settings.PAGINATE_BY

    def get_course_subjects_filterset(self):
        coordinator_course = self.request.user.person.coordinator_person.course
        course_subjects = Subject.objects.filter(course=coordinator_course, committee_subject=None)
        return SubjectFilterSet(data=self.request.GET, queryset=course_subjects)

    def get_paginated_subjects(self):
        filtered_courses_queryset = self.get_course_subjects_filterset().qs
        return Paginator(object_list=filtered_courses_queryset, per_page=self.paginate_courses_by)

    def get_current_subjects_page(self):
        currnet_page = self.request.GET.get("page", 1)
        paginator = self.get_paginated_subjects()
        return paginator.page(currnet_page)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.get_course_subjects_filterset()
        context["paginator"] = self.get_paginated_subjects()
        context["current_page"] = self.get_current_subjects_page().number
        context["page_obj"] = self.get_current_subjects_page()
        context["object_list"] = context["paginator"].object_list
        return context

    @transaction.atomic
    def form_valid(self, form):
        committee = form.save(commit=False)
        committee.created_by = self.request.user
        committee.updated_by = self.request.user
        committee.coordinator = self.request.user.person.coordinator_person
        return super().form_valid(form)


class CommitteeListView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, FilteredListView):
    model = Committee
    template_name = "academics/coordinators/committee_filter.html"
    filterset_class = CommitteeFilterSet
    paginate_by = settings.PAGINATE_BY

    def get_queryset(self):
        queryset = super().get_queryset()
        coordinator_course = self.request.user.person.coordinator_person.course
        return queryset.filter(subject__course__in=[coordinator_course])


class CommitteAddTeachersView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, SuccessMessageMixin, UpdateView):
    template_name = "academics/coordinators/add_teachers_to_committee.html"
    form_class = AddTeachersToCommitteeForm
    model = Committee
    success_message = _("Banca atualizada com sucesso!")
    success_url = None
    paginate_teachers_by = settings.PAGINATE_BY

    def get_success_url(self):
        return reverse("academics:committees_add_teachers", kwargs={"pk": self.object.pk})

    def get_subject_teachers_filterset(self):
        committee_subject = self.get_object().subject
        teachers = Teacher.objects.filter(subjects__in=[committee_subject]).exclude(
            committee_teachers__in=[self.object]
        )
        return TeacherFilterSet(data=self.request.GET, queryset=teachers)

    def get_already_added_teachers(self):
        committee = self.get_object()
        return Teacher.objects.filter(committee_teachers__in=[committee])

    def get_paginated_teachers(self):
        filtered_teachers_queryset = self.get_subject_teachers_filterset().qs
        return Paginator(object_list=filtered_teachers_queryset, per_page=self.paginate_teachers_by)

    def get_current_teachers_page(self):
        currnet_page = self.request.GET.get("page", 1)
        paginator = self.get_paginated_teachers()
        return paginator.page(currnet_page)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter"] = self.get_subject_teachers_filterset()
        context["paginator"] = self.get_paginated_teachers()
        context["current_page"] = self.get_current_teachers_page().number
        context["page_obj"] = self.get_current_teachers_page()
        context["object_list"] = context["paginator"].object_list
        context["added_teachers"] = self.get_already_added_teachers()
        return context


class CommitteeDeleteView(LoginRequiredMixin, UserIsCourseCoordinatorTestMixin, SuccessMessageMixin, DeleteView):
    model = Committee
    success_message = _("Banca exlcuída com sucesso!")
    success_url = reverse_lazy("academics:committees_list")
    template_name = "academics/coordinators/committee_check_delete.html"

ccam/academics/seac/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView

from ccam.academics.filters import SeacKnowledgeCertificateFilterSet, SubjectDispensalFilterSet
from ccam.academics.forms import RejectStudentKnowledgeCertificateForm, RejectStudentSubjectDispensalForm
from ccam.academics.models import KnowledgeCertificate, SubjectDispensal
from ccam.core.views import FilteredListView
from ccam.people.mixins import UserIsSeacEmployeeTestMixin


class SeacKnowledgeCertificatesListView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, FilteredListView):
    model = KnowledgeCertificate
    filterset_class = SeacKnowledgeCertificateFilterSet
    template_name = "academics/seac_academics/seac_view_knowledge_certificates.html"
    paginate_by = settings.PAGINATE_BY


class SeacSubjectDispensalListView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, FilteredListView):
    model = SubjectDispensal
    filterset_class = SubjectDispensalFilterSet
    template_name = "academics/seac_academics/seac_view_courses_dispensal.html"
    paginate_by = settings.PAGINATE_BY


class SeacKnowledgeCertificateUpdateView(
    LoginRequiredMixin, UserIsSeacEmployeeTestMixin, SuccessMessageMixin, UpdateView
):
    model = KnowledgeCertificate
    fields = ("status", "justification")
    template_name = "academics/seac_academics/knowledge_certificates_student_details.html"
    context_object_name = "knowledge_certificate"
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("academics:knowledge_certificates")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subjects"] = context["knowledge_certificate"].subjects.all()
        return context


class SeacCoursesDispensalUpdateView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, SuccessMessageMixin, UpdateView):
    model = SubjectDispensal
    fields = ("status", "justification")
    template_name = "academics/seac_academics/courses_dispensal_student_details.html"
    context_object_name = "course_dispensal"
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("academics:courses_dispensal")


class RejectStudentKnowledgeCertificateFormView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, UpdateView):
    model = KnowledgeCertificate
    template_name = "academics/seac_academics/rejected_kc_modal.html"
    form_class = RejectStudentKnowledgeCertificateForm
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("people:seac:home")


class RejectStudentSubjectDispensalFormView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, UpdateView):
    model = SubjectDispensal
    template_name = "academics/seac_academics/rejected_cd_modal.html"
    form_class = RejectStudentSubjectDispensalForm
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("people:seac:home")

ccam/academics/views.py
from django.views.generic import TemplateView

from ccam.academics.models import Course


class CourseSubjects(TemplateView):
    template_name = "academics/_course_subjects.html"

    def get_course_id(self):
        course_id = self.request.GET.get("teacher-course")
        # If a blank option is selected, course_id comes as '' (falsy value)
        return course_id if course_id else 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_id = self.get_course_id()
        course = Course.objects.filter(id=course_id)

        if course.exists():
            subjects = course.first().subjects.all()
        else:
            subjects = []
        context["course_subjects"] = subjects
        return context

ccam/academics/templates/academics/seac_academics/_courses_dispensal_student_details.html
{% load static %}
{% load button %}

<section class="prof-pic-and-name">
  <img src="{{ course_dispensal.student.person.profile_picture.url }}"
       alt="Ernie and Bert from Sesame Street"
       width="150"
       height="151" />
  <span>{{ course_dispensal.student.person.name }}</span>
</section>
<section class="person-info">
  <div>
    <span><b>Matrícula:</b> {{ course_dispensal.student.person.registration }}</span>
    <span><b>Curso:</b> {{ course_dispensal.student.course.name }}</span>
    <span><b>Período:</b> {{ course_dispensal.student.current_grade_semester }}</span>
    <span><b>Disciplinas IFRN:</b> {{ course_dispensal.get_subjects_names }}</span>
  </div>
  <div>
    <span><b>Fone: </b>{{ course_dispensal.student.person.phone_number }}</span>
    <span><b>E-mail: </b>{{ course_dispensal.student.person.email }}</span>
    <span><b>Status: </b>{{ course_dispensal.status }}</span>
  </div>
</section>
<div class="assessment-buttons">
  <form method="post" class="assessment-buttons">
    {% csrf_token %}
    {% button button_text="Aprovar" color_class="green-svg" icon="done_all" name=form.status.html_name value=form.status.field.choices.0.0 type="submit" %}
    <button hx-get="{% url 'academics:reject_subject_dispensal' course_dispensal.pk %}" hx-swap="innerHTML" hx-target="#confirmation-modal" hx-trigger="click" class="ccam-button confirmation-modal-trigger">
      Rejeitar
      <span class="material-symbols-outlined red-svg">
        cancel
      </span>
    </button>
  </form>
</div>

{% include "core/_confirmation_modal.html" %}

ccam/academics/templates/academics/seac_academics/courses_dispensal_student_details.html
{% extends 'base.html' %}
{% load breadcrumb_item %}

{% block breadcrumb_items %}
  {% breadcrumb_item text="Home" icon="home" href='people:seac:home' %}
  {% breadcrumb_item text="Aproveitamento de Disciplina" icon="export_notes" href='academics:courses_dispensal' %}
  {% breadcrumb_item text="Visualizar" icon="visibility" active=True last_item=True %}
{% endblock breadcrumb_items %}

{% block content %}
  <main id="container"
        class="centered-content student-details-center-vertical">
    {% include 'academics/seac_academics/_courses_dispensal_student_details.html' %}
  </main>
{% endblock content %}

ccam/academics/templates/academics/seac_academics/knowledge_certificates_student_details.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}
{% load button %}

{% block breadcrumb_items %}
  {% breadcrumb_item text="Home" icon="home" href='people:seac:home' %}
  {% breadcrumb_item text="Certificação de Conhecimentos" image_icon=True icon_path='people/images/icons/diploma.svg' href='academics:knowledge_certificates' %}
  {% breadcrumb_item text="Visualizar Solicitação" icon="visibility" active=True last_item=True %}
{% endblock breadcrumb_items %}

{% block content %}
  <main id="container"
        class="centered-content student-details-center-vertical">
    <section class="prof-pic-and-name">
      <img src="{{ knowledge_certificate.student.person.profile_picture.url }}"
          alt="Ernie and Bert from Sesame Street"
          width="150"
          height="151" />
      <span>{{ knowledge_certificate.student.person.name }}</span>
    </section>
    <section class="person-info">
      <div>
        <span><b>Matrícula:</b> {{ knowledge_certificate.student.person.registration }}</span>
        <span><b>Curso:</b> {{ knowledge_certificate.student.course.name }}</span>
        <span><b>Período:</b> {{ knowledge_certificate.student.current_grade_semester }}º</span>
        <span><b>Disciplinas:</b> 
          {% for subject in subjects %}
            {{ subject.name }},
          {% endfor %}
        </span>
      </div>
      <div>
        <span><b>Fone: </b>{{ knowledge_certificate.student.person.phone_number }}</span>
        <span><b>E-mail: </b>{{ knowledge_certificate.student.person.email }}</span>
        <span><b>Status: </b>{{ knowledge_certificate.status }}</span>
      </div>
    </section>
    <div class="assessment-buttons">
      <form method="post">
        {% csrf_token %}
        {% button button_text="Aprovar" color_class="green-svg" icon="done_all" name=form.status.html_name value=form.status.field.choices.0.0 type="submit" %}
      </form>
      <button hx-get="{% url 'academics:reject_knowledge_certificate' knowledge_certificate.pk %}" hx-swap="innerHTML" hx-target="#confirmation-modal" hx-trigger="click" class="ccam-button confirmation-modal-trigger">
        Rejeitar
        <span class="material-symbols-outlined red-svg">
          cancel
        </span>
      </button>
    </div>
    </main>

    {% include "core/_confirmation_modal.html" %}
{% endblock content %}

ccam/academics/templates/academics/seac_academics/rejected_cd_modal.html
{% load button %}
<form action="{% url 'academics:reject_subject_dispensal' object.pk %}" method="post">
    {% csrf_token %}
    <h1>Escreva o motivo da reprovação</h1>
    <span>Reprovar a solicitação irá enviar um e-mail para o estudante para que ele possa fazer uma nova soliticação com os dados corrigidos.</span>
    <textarea name="justification" id="justification" cols="30" rows="10" placeholder="O fone está incorreto..." style="resize: none; padding: 20px;"></textarea>
    <div class="assessment-buttons">
        {% button button_text="Enviar" color_class="green-svg" icon="done_all" name=form.status.html_name value=form.status.field.choices.2.0 type="submit" %}
        {% button button_text="Cancelar" color_class="red-svg" icon="cancel" id="close-modal-button" type="button" %}
    </div>
</form>

ccam/academics/templates/academics/seac_academics/rejected_kc_modal.html
{% load button %}
<form action="{% url 'academics:reject_knowledge_certificate' object.pk %}" method="post">
    {% csrf_token %}
    <h1>Escreva o motivo da reprovação</h1>
    <span>Reprovar a solicitação irá enviar um e-mail para o estudante para que ele possa fazer uma nova soliticação com os dados corrigidos.</span>
    <textarea name="justification" id="justification" cols="30" rows="10" placeholder="O fone está incorreto..." style="resize: none; padding: 20px;"></textarea>
    <div class="assessment-buttons">
        {% button button_text="Enviar" color_class="green-svg" icon="done_all" name=form.status.html_name value=form.status.field.choices.2.0 type="submit" %}
        {% button button_text="Cancelar" color_class="red-svg" icon="cancel" id="close-modal-button" type="button" %}
    </div>
</form>

ccam/academics/templates/academics/seac_academics/rejected_modal.html
{% load button %}
<form action="{% url 'academics:reject_knowledge_certificate' object.pk %}" method="post">
    {% csrf_token %}
    <h1>Escreva o motivo da reprovação</h1>
    <span>Reprovar a solicitação irá enviar um e-mail para o estudante para que ele possa fazer uma nova soliticação com os dados corrigidos.</span>
    <textarea name="justification" id="justification" cols="30" rows="10" placeholder="O fone está incorreto..."></textarea>
    <div class="assessment-buttons">
        {% button button_text="Enviar" color_class="green-svg" icon="done_all" name=form.status.html_name value=form.status.field.choices.2.0 type="submit" %}
        <button class="ccam-button" id="close-modal-button">
            Cancelar
            <span class="material-symbols-outlined red-svg">
                cancel
            </span>
        </button>
    </div>
</form>

ccam/academics/templates/academics/seac_academics/seac_view_courses_dispensal.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}
{% load simple_table_button %}
{% load button %}

{% block breadcrumb_items %}
  {% breadcrumb_item text="Home" icon="home" href='people:seac:home' %}
  {% breadcrumb_item text="Aproveitamento de Disciplinas" icon="export_notes" active=True last_item=True %}
{% endblock breadcrumb_items %}

{% block content %}
  <main id="container" class="left-aligned-content">
    <main class="view-table-section">
      <header class="header-with-icon">
        <img src="{% static 'people/images/icons/filter.svg' %}"
            alt="A classic, green filter icon"
            width="35"
            height="35"
            class="green-svg" />
        <h2>Filtros</h2>
      </header>
      <form method="get" class="filter-section">
        <div class="fields-container">
          <div class="ccam-input">
            {{ filter.form.registration.label_tag }}
            {{ filter.form.registration }}
          </div>
          <div class="ccam-input">
            {{ filter.form.created_at.label_tag }}
            <input type="date" name="{{ filter.form.created_at.html_name }}" id="{{ filter.form.created_at.id_for_label }}"/>
          </div>
          <div class="ccam-input">
            {{ filter.form.student_name.label_tag }}
            {{ filter.form.student_name }}
          </div>
          <div class="ccam-input">
            {{ filter.form.status.label_tag }}
            <div class="ccam-select">
              {{ filter.form.status }}
            </div>
          </div>
        </div>
        {% button button_text="Filtrar" icon="filter_alt" %}
      </form>
      <header class="header-with-icon padding-from-content">
        <img src="{% static 'people/images/icons/dataTable.svg' %}"
            alt="A green icon representation of a table with data on it."
            width="35"
            height="35"
            class="green-svg" />
        <h2>Solicitações</h2>
      </header>
      <section>
        <table class="ccam-table">
          <thead>
            <tr>
              <th>
                <img width="30"
                    height="30"
                    src="{% static 'people/images/icons/signatureIcon.svg' %}"
                    alt="A green signature icon" />
                Nome
              </th>
              <th>
                <img width="30"
                    height="30"
                    src="{% static 'people/images/icons/personVCard.svg' %}"
                    alt="A green verification card containing a person" />
                Matrícula
              </th>
              <th>
                <img width="30"
                    height="30"
                    src="{% static 'people/images/icons/calendarIcon.svg' %}"
                    alt="A green and simple calendar that marks an event." />
                Data de Submissão
              </th>
              <th>
                <img width="30"
                    height="30"
                    src="{% static 'people/images/icons/actionIcon.svg' %}"
                    alt="A green settings icon indicating actions you can take on a specific table." />
                Ações
              </th>
            </tr>
          </thead>
          <tbody>
            {% for subject_dispensal in object_list %}
            {% if subject_dispensal.status == "PR" %}
            <tr>
              <td>{{ subject_dispensal.student.person.name }}</td>
              <td>{{ subject_dispensal.student.person.registration }}</td>
              <td>{{ subject_dispensal.created_at|date:"d/m/Y" }}</td>
              <td>
                {% simple_table_button color_class='green-text' icon='visibility' abs_url=subject_dispensal.get_absolute_url %}
              </td>
            </tr>
            {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </section>
    </main>
  </main>
{% endblock content %}