ccam/academics/seac/urls.py
from django.urls import path

from ccam.academics.seac import views

urlpatterns = [
    path(
        "knowledge-certificates/list", views.SeacKnowledgeCertificatesListView.as_view(), name="knowledge_certificates"
    ),
    path("courses-dispensal/list", views.SeacSubjectDispensalListView.as_view(), name="courses_dispensal"),
    path(
        "knowledge-certificates/detail/<int:pk>/",
        views.SeacKnowledgeCertificateUpdateView.as_view(),
        name="knowledge_certificate_detail",
    ),
    path(
        "courses-dispensal/detail/<int:pk>",
        views.SeacCoursesDispensalUpdateView.as_view(),
        name="courses_dispensal_detail",
    ),
    path(
        "knowledge-certificate-rejection/<int:pk>/",
        views.RejectStudentKnowledgeCertificateFormView.as_view(),
        name="reject_knowledge_certificate",
    ),
    path(
        "subject-dispensal-rejection/<int:pk>/",
        views.RejectStudentSubjectDispensalFormView.as_view(),
        name="reject_subject_dispensal",
    ),
]

ccam/academics/students/urls.py
from django.urls import path

from ccam.academics.students import views

urlpatterns = [
    path(
        "knowledge-certificates/create/",
        views.KnowledgeCertificateCreateView.as_view(),
        name="knowledge_certificates_create",
    ),
    path(
        "knowledge-certificates/list/",
        views.KnowledgeCertificateListView.as_view(),
        name="knowledge_certificates_list",
    ),
    path("subject-dispensals/create/", views.SubjectDispensalCreateView.as_view(), name="subject_dispensals_create"),
    path("subject-dispensals/list/", views.SubjectDispensalListView.as_view(), name="subject_dispensals_list"),
    path(
        "subject-dispensals/check-justification/<int:pk>/",
        views.SubjectDispensalApprovalCheckView.as_view(),
        name="subject_dispensal_denial_check",
    ),
    path(
        "knowledge-certificates/check-justification/<int:pk>/",
        views.KnowledgeCertificateApprovalCheckView.as_view(),
        name="knowledge_certificate_denial_check",
    ),
]

ccam/academics/urls.py
from django.urls import path

from ccam.academics.coordinators.urls import urlpatterns as coordinators_urls
from ccam.academics.seac.urls import urlpatterns as seac_urls
from ccam.academics.students.urls import urlpatterns as students_urls
from ccam.academics.teachers.urls import urlpatterns as teachers_urls
from ccam.academics.views import CourseSubjects

app_name = "academics"

urlpatterns = [path("course-subjects/", CourseSubjects.as_view(), name="course_subjects")]

urlpatterns += seac_urls
urlpatterns += coordinators_urls
urlpatterns += students_urls
urlpatterns += teachers_urls

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ccam.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("people/", include("people.urls")),
    path("academics/", include("academics.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ccam/academics/models.py
from datetime import date

from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils.text import get_text_list
from django.utils.translation import gettext_lazy as _

from ccam.academics.utils import get_subject_dispensal_files_dir
from ccam.core.models import BaseModel, EducationalLevel, GradeSemester


class Course(BaseModel):
    name = models.CharField(max_length=280, verbose_name=_("Nome do curso"))
    duration = models.SmallIntegerField(
        verbose_name=_("Duração (em anos/períodos)"), validators=[MaxValueValidator(8)]
    )
    coordinator = models.OneToOneField(
        "coordinators.Coordinator", on_delete=models.CASCADE, related_name="course", null=True
    )

    class Meta:
        verbose_name = _("Curso")
        verbose_name_plural = _("Cursos")

    def __str__(self) -> str:
        return f"{self.name}"


class Subject(BaseModel):
    name = models.CharField(max_length=40, verbose_name=_("Nome da Disciplina"))
    course = models.ManyToManyField(Course, related_name="subjects", verbose_name=_("Cursos"))
    grade_semester_availability = models.PositiveSmallIntegerField(
        verbose_name=_("Ano/Período"), choices=GradeSemester.choices
    )
    educational_level = models.CharField(
        max_length=4, choices=EducationalLevel.choices, verbose_name=_("Nível Educacional")
    )

    class Meta:
        verbose_name = _("Disciplina")
        verbose_name_plural = _("Disciplinas")

    def __str__(self):
        return f"{self.name} - {self.get_educational_level_display()}"

    def get_courses_names(self):
        courses_names = list(self.course.values_list("name", flat=True))
        courses_names = get_text_list(courses_names, "e")
        return courses_names

    def get_absolute_url(self):
        return reverse("academics:subjects_detail", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse("academics:subjects_update", kwargs={"pk": self.pk})


class KnowledgeCertificate(BaseModel):
    class Status(models.TextChoices):
        APPROVED = "AP", _("Aprovado")
        ANALYZING = "PR", _("Em análise")
        REJECTED = "ERR", _("Recusado")

    assessed_by = models.ForeignKey(
        "seac.SEACStaff", on_delete=models.CASCADE, related_name="assessor", blank=True, null=True
    )
    student = models.ForeignKey(
        "students.Student", on_delete=models.CASCADE, related_name="student_knowledge_certificates"
    )
    subjects = models.ManyToManyField(Subject, related_name="knowledge_certificates", through="KnowledgeCGrades")
    status = models.CharField(max_length=3, choices=Status.choices, default=Status.ANALYZING, verbose_name=_("Status"))
    justification = models.TextField(blank=True)

    class Meta:
        verbose_name = _("Certificação de Conhecimento")
        verbose_name_plural = _("Certificação de Conhecimentos")
        constraints = [
            models.UniqueConstraint(
                fields=["student", "status"], condition=models.Q(status="PR"), name="one-pending-request-per-student"
            )
        ]

    def get_subjects_names(self):
        subjects_names = list(self.subjects.values_list("name", flat=True))
        subjects_names = get_text_list(subjects_names, "e")
        return subjects_names

    def __str__(self):
        return f"{self.subjects}, {self.student.person.name} - {self.student.person.registration}"

    def get_absolute_url(self):
        return reverse("academics:knowledge_certificate_detail", kwargs={"pk": self.pk})


class KnowledgeCGrades(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="knowledge_certificate_subject")
    knowledge_certificate = models.ForeignKey(
        KnowledgeCertificate, on_delete=models.CASCADE, related_name="specific_knowledge_certificate"
    )
    grade = models.PositiveSmallIntegerField(
        verbose_name=_("Nota"), validators=[MaxValueValidator(100)], blank=True, null=True
    )

    class Meta:
        verbose_name = _("CertificaçãoCNotas")
        verbose_name_plural = _("CertificaçãoCNotas")

    def __str__(self):
        return (
            f"{self.subject};"
            f"\n{self.knowledge_certificate.student.person.name};"
            f"\n{self.knowledge_certificate.student.person.registration}"
        )


class SubjectDispensal(BaseModel):
    class Status(models.TextChoices):
        APPROVED = "AP", _("Aprovado")
        ANALYZING = "PR", _("Em análise")
        REJECTED = "ERR", _("Recusado")

    assessed_by = models.ForeignKey(
        "seac.SEACStaff", on_delete=models.CASCADE, related_name="subject_dispensal_assessor", blank=True, null=True
    )
    student = models.ForeignKey("students.Student", on_delete=models.CASCADE, related_name="subject_dispensal_student")
    subjects = models.ManyToManyField(
        Subject, related_name="subject_dispensal_subjects", through="SubjectDGrades", verbose_name=_("Disciplinas")
    )
    justification = models.TextField(blank=True)
    status = models.CharField(max_length=3, choices=Status.choices, default=Status.ANALYZING, verbose_name=_("Status"))
    previous_university_ppc = models.FileField(
        upload_to=get_subject_dispensal_files_dir, verbose_name=_("PPC da Antiga Universidade")
    )
    previous_university_grades = models.FileField(
        upload_to=get_subject_dispensal_files_dir, verbose_name=_("Histórico da Antiga Universidade")
    )

    class Meta:
        verbose_name = _("Aproveitamento de Disciplina")
        verbose_name_plural = _("Aproveitamento de Disciplinas")
        constraints = [
            models.UniqueConstraint(
                fields=["student", "status"],
                condition=models.Q(status="PR"),
                name="one-pending-subject-dispensal-request-per-student",
            )
        ]

    def __str__(self):
        return f"{self.subjects}, {self.student.person.name} - {self.student.person.registration}"

    def get_subjects_names(self):
        subjects_names_list = list(self.subjects.values_list("name", flat=True))
        subjects_names = get_text_list(subjects_names_list, "e")
        return subjects_names

    def get_absolute_url(self):
        return reverse("academics:courses_dispensal_detail", kwargs={"pk": self.pk})


class SubjectDGrades(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="subject_dispensal_subject")
    subject_dispensal = models.ForeignKey(
        SubjectDispensal, on_delete=models.CASCADE, related_name="specific_subject_dispensal"
    )
    compatibility = models.PositiveSmallIntegerField(
        verbose_name=_("Compatibilidade"), validators=[MaxValueValidator(100)], blank=True, null=True
    )

    class Meta:
        verbose_name = _("AproveitamentoDCompatibilidades")
        verbose_name_plural = _("AproveitamentoDCompatibilidades")

    def __str__(self):
        return (
            f"{self.subject};"
            f"\n{self.subject_dispensal.student.person.name};"
            f"\n{self.subject_dispensal.student.person.registration}"
        )


class Committee(BaseModel):
    coordinator = models.ForeignKey(
        "coordinators.Coordinator", on_delete=models.CASCADE, related_name="committee_coordinator"
    )
    teachers = models.ManyToManyField("teachers.Teacher", related_name="committee_teachers", blank=True)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, related_name="committee_subject", verbose_name="Disciplina"
    )

    class Meta:
        verbose_name = _("Banca")
        verbose_name_plural = _("Bancas")

    def __str__(self):
        return f"{self.subject.name}"

    def get_teachers_names(self):
        teachers_names = list(self.teachers.values_list("person__name", flat=True))
        teachers_names = get_text_list(teachers_names, "e")
        return teachers_names

ccam/academics/seac/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView

from ccam.academics.filters import SeacKnowledgeCertificateFilterSet, SubjectDispensalFilterSet
from ccam.academics.forms import RejectStudentKnowledgeCertificateForm, RejectStudentSubjectDispensalForm
from ccam.academics.models import KnowledgeCertificate, SubjectDispensal
from ccam.core.views import FilteredListView
from ccam.people.mixins import UserIsSeacEmployeeTestMixin


class SeacKnowledgeCertificatesListView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, FilteredListView):
    model = KnowledgeCertificate
    filterset_class = SeacKnowledgeCertificateFilterSet
    template_name = "academics/seac_academics/seac_view_knowledge_certificates.html"
    paginate_by = settings.PAGINATE_BY


class SeacSubjectDispensalListView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, FilteredListView):
    model = SubjectDispensal
    filterset_class = SubjectDispensalFilterSet
    template_name = "academics/seac_academics/seac_view_courses_dispensal.html"
    paginate_by = settings.PAGINATE_BY


class SeacKnowledgeCertificateUpdateView(
    LoginRequiredMixin, UserIsSeacEmployeeTestMixin, SuccessMessageMixin, UpdateView
):
    model = KnowledgeCertificate
    fields = ("status", "justification")
    template_name = "academics/seac_academics/knowledge_certificates_student_details.html"
    context_object_name = "knowledge_certificate"
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("academics:knowledge_certificates")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subjects"] = context["knowledge_certificate"].subjects.all()
        return context


class SeacCoursesDispensalUpdateView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, SuccessMessageMixin, UpdateView):
    model = SubjectDispensal
    fields = ("status", "justification")
    template_name = "academics/seac_academics/courses_dispensal_student_details.html"
    context_object_name = "course_dispensal"
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("academics:courses_dispensal")


class RejectStudentKnowledgeCertificateFormView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, UpdateView):
    model = KnowledgeCertificate
    template_name = "academics/seac_academics/rejected_kc_modal.html"
    form_class = RejectStudentKnowledgeCertificateForm
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("people:seac:home")


class RejectStudentSubjectDispensalFormView(LoginRequiredMixin, UserIsSeacEmployeeTestMixin, UpdateView):
    model = SubjectDispensal
    template_name = "academics/seac_academics/rejected_cd_modal.html"
    form_class = RejectStudentSubjectDispensalForm
    success_message = _("Solicitação atualizada com sucesso")
    success_url = reverse_lazy("people:seac:home")

ccam/academics/views.py
from django.views.generic import TemplateView

from ccam.academics.models import Course


class CourseSubjects(TemplateView):
    template_name = "academics/_course_subjects.html"

    def get_course_id(self):
        course_id = self.request.GET.get("teacher-course")
        # If a blank option is selected, course_id comes as '' (falsy value)
        return course_id if course_id else 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_id = self.get_course_id()
        course = Course.objects.filter(id=course_id)

        if course.exists():
            subjects = course.first().subjects.all()
        else:
            subjects = []
        context["course_subjects"] = subjects
        return context

ccam/academics/templates/academics/teacher_academics/_course_progress_assessment_modal.html
{% extends "academics/teacher_academics/base_assessment_modal.html" %}

{% block message_input %}
    <section class="d-flex flex-column justify-content-center align-items-center">
        <p class="fw-bold">Após análise, a disciplina é <span class="green-text">aproveitável</span>?</p>
        <div class="ccam-radio-input d-flex flex-column">
            <div class="d-flex" id="radio-group">
              <div class="d-flex">
                <input type="radio" name="course_progress_possible" id="yes" value="1" />
                <label class="fw-bold" for="yes">Sim</label>
              </div>
              <div class="d-flex">
                <input type="radio" name="course_progress_possible" id="no" value="2" />
                <label class="fw-bold" for="no">Não</label>
              </div>
            </div>
          </div>
    </section>
{% endblock message_input %}

ccam/academics/templates/academics/teacher_academics/_knowledge_certificate_assessment_modal.html
{% extends "academics/teacher_academics/base_assessment_modal.html" %}

{% block message_input %}
    <section class="d-flex flex-column justify-content-center align-items-center">
        <p class="fw-bold">Digite a <span class="green-text">nota</span> obtida pelo aluno na prova de certiciação de conhecimento</p>
        <div class="ccam-input align-items-center">
            <input class="text-center w-50" type="number" name="grade" id="grade" />
        </div>
    </section>
{% endblock message_input %}

ccam/academics/templates/academics/teacher_academics/base_assessment_modal.html
<dialog id="assessment-dialog" class="m-auto w-50">
    {% block message_input %}
    {% endblock message_input %}
    <section class="w-100 d-flex justify-content-evenly pt-4">
        {% include "core/_button.html" with button_text="Avaliar" icon_path='core/images/icons/approval.svg' alt="Green approval tool" color_class="green-svg" custom_class="w-25" %}
        {% include "core/_button.html" with button_text="Cancelar" icon_path='core/images/icons/cancel.svg' alt="Green approval tool" color_class="red-svg" id="assessment-dialog-cancel" custom_class="w-25" %}
    </section>
</dialog>

ccam/academics/templates/academics/teacher_academics/course_progress_assessments.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}

{% block breadcrumb_items %}
  {% breadcrumb_item text="Home" icon="home" href='people:teachers:home' %}
  {% breadcrumb_item text="Aproveitamento de Disciplina" icon="export_notes" href='academics:subject_course_progress_list' %}
  {% breadcrumb_item text="Avaliação" icon="approval" active=True last_item=True %}
{% endblock breadcrumb_items %}

{% block content %}
  <main id="container" class="view-table-section">
    <header class="header-with-icon">
      <img src="{% static 'people/images/icons/filter.svg' %}"
           alt="A classic, green filter icon"
           width="35"
           height="35"
           class="green-svg" />
      <h2>Filtros</h2>
    </header>
    <section class="filter-section">
      <div class="fields-container">
        <div class="ccam-input">
          <label for="student-id">Matrícula</label>
          <input type="text" name="student-id" id="student-id" />
        </div>
      </div>
      {% include "core/_button.html" with button_text="Filtrar" color_class="green-svg" icon_path='people/images/icons/filter.svg' alt_text="A classic green filter object" %}
    </section>
    <header class="header-with-icon padding-from-content">
      <img src="{% static 'people/images/icons/dataTable.svg' %}"
           alt="A green school backpack"
           width="35"
           height="35"
           class="green-svg" />
      <h2>Alunos Para Avaliar</h2>
    </header>
    <section>
      <table class="ccam-table">
        <thead>
          <tr>
            <th>
              <img src="{% static 'people/images/icons/signatureIcon.svg' %}"
                   alt="A handwritten signature" />
              Nome
            </th>
            <th>
              <img src="{% static 'people/images/icons/personVCard.svg' %}"
                   alt="A VCard" />
              CPF
            </th>
            <th>
              <img src="{% static 'people/images/icons/badge.svg' %}"
                   alt="A badge containing ID information" />
              Matrícula
            </th>
            <th>
              <img src="{% static 'images/icons/email.svg' %}"
                   alt="A mail letter envelope" />
              Email
            </th>
            <th>
              <img src="{% static 'images/icons/course.svg' %}"
                   alt="A feather pen writing on a scroll" />
              Curso
            </th>
            <th>
              <img src="{% static 'people/images/icons/actionIcon.svg' %}"
                   alt="A green settings icon indicating actions you can take on a specific table" />
              Ações
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
        </tbody>
      </table>
    </section>
    {% include "core/_table_pagination.html" %}
    {% include "academics/teacher_academics/_course_progress_assessment_modal.html" %}
  </main>
{% endblock content %}

ccam/academics/templates/academics/teacher_academics/knowledge_certificate_assessment.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}

{% block breadcrumb_items %}
  {% breadcrumb_item text="Home" icon="home" href='people:teachers:home' %}
  {% breadcrumb_item text="Certificação de Conhecimento" image_icon=True icon_path='people/images/icons/diploma.svg' href='academics:subject_list' %}
  {% breadcrumb_item text="Avaliação" icon="approval" active=True last_item=True %}
{% endblock breadcrumb_items %}

{% block content %}
  <main id="container" class="view-table-section">
    <header class="header-with-icon">
      <img src="{% static 'people/images/icons/filter.svg' %}"
           alt="A classic, green filter icon"
           width="35"
           height="35"
           class="green-svg" />
      <h2>Filtros</h2>
    </header>
    <section class="filter-section">
      <div class="fields-container">
        <div class="ccam-input">
          <label for="student-id">Matrícula</label>
          <input type="text" name="student-id" id="student-id" />
        </div>
      </div>
      {% include "core/_button.html" with button_text="Filtrar" color_class="green-svg" icon_path='people/images/icons/filter.svg' alt_text="A classic green filter object" %}
    </section>
    <header class="header-with-icon padding-from-content">
      <img src="{% static 'people/images/icons/dataTable.svg' %}"
           alt="A green school backpack"
           width="35"
           height="35"
           class="green-svg" />
      <h2>Alunos Para Avaliar</h2>
    </header>
    <section>
      <table class="ccam-table">
        <thead>
          <tr>
            <th>
              <img src="{% static 'people/images/icons/signatureIcon.svg' %}"
                   alt="A handwritten signature" />
              Nome
            </th>
            <th>
              <img src="{% static 'people/images/icons/personVCard.svg' %}"
                   alt="A VCard" />
              CPF
            </th>
            <th>
              <img src="{% static 'people/images/icons/badge.svg' %}"
                   alt="A badge containing ID information" />
              Matrícula
            </th>
            <th>
              <img src="{% static 'images/icons/email.svg' %}"
                   alt="A mail letter envelope" />
              Email
            </th>
            <th>
              <img src="{% static 'images/icons/course.svg' %}"
                   alt="A feather pen writing on a scroll" />
              Curso
            </th>
            <th>
              <img src="{% static 'people/images/icons/actionIcon.svg' %}"
                   alt="A green settings icon indicating actions you can take on a specific table" />
              Ações
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
          <tr>
            <td>Ernie & Bert</td>
            <td>123.456.789-10</td>
            <td>20221094040191</td>
            <td>ernie.bert@sesame.com</td>
            <td>TADS</td>
            <td>
                {% include 'core/_table_button.html' with button_text="Avaliar" color_class="green-svg" icon_path='core/images/icons/approval.svg' alt_text="A green eye icon" custom_class="assessment-dialog-trigger" %}
            </td>
          </tr>
        </tbody>
      </table>
    </section>
    {% include "core/_table_pagination.html" %}
    {% include "academics/teacher_academics/_knowledge_certificate_assessment_modal.html" %}
  </main>
{% endblock content %}